kasi/urls.py
from django.urls import path
from . import views

app_name = 'kasi'
urlpatterns = [
path('', views.homePage, name='home'),
path('comment', views.comment, name = 'comment')
]

kasiBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kasi/', include('kasi.urls'))
]

kasi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.
class Stories(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    name = models.CharField(max_length=20)
    summary = models.CharField(max_length = 80, blank=False)
    published_date = models.DateTimeField()
    def __str__(self):
        return self.name
class Comment(models.Model):
    #comment = models.ForeignKey(Stories, on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, default= None)
    comment_text = models.TextField(blank = False)

    def __str__(self):
        return self.comment_text

kasi/forms.py
from django import forms
from django.forms import ModelForm
from .models import Stories, Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text', 'user']

kasi/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Stories, Comment
from .forms import CommentForm
from django.views.generic import TemplateView

# Create your views here.


def homePage(request):
    template_name = 'kasi/home.html'
    story_list = Stories.objects.order_by('pk')
    comments = Comment.objects.order_by('pk')
    return render(request, template_name, {'story_list':story_list, 'comments':comments})

def comment(request):
    if request.method =='POST':
       form = CommentForm(request.POST)
       if form.is_valid():
          form.save()
          return redirect('kasi:home')
    else:
        form = CommentForm()
        return render(request, 'kasi/form.html', {'form':form})

kasi/templates/kasi/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'kasi/blog.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <title></title>
  </head>

  <body>
    <div class="heading">
        <h1>My Dream Voice</h1>
    </div>
    <div class="intro container">
      <h2>Hello! I am Kashyap.</h2>
      <img src="{% static 'kasi/images/kasi.jpg' %}" alt="" height="400px" width="300px">
    </div>
    <div class="description container">
      <h3>"Me"</h3>
      <p>I am a regular street food loving Mumbaiker who has crazy and amazing dreams which I would love to share with everyone. </p>
      <p>My Stories can turn you to a good mood. So beware to keep Icecream before you start. Trust me you will crave for it.</p>
    </div>
    {% block Stories %}
    {% endblock %}
    <div class="contact container">
      <p>Ok!</p>
      <p> How do you feel?</p>
      <p>Feel free to comment and share your thoughts!</p>
    </div>
    {% block Comment %}
    {% endblock %}

  </body>
</html>

kasi/templates/kasi/form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form method="post">
      {% csrf_token %}
      {{ form.as_ul }}
      <button type="submit" name="button">submit</button>
    </form>
    
  </body>
</html>

kasi/templates/kasi/home.html
{% extends 'kasi/base.html' %}
{% load static %}

{% block Stories %}
<div class="myStories container">
  {% for story in story_list %}
   <div class="trueWinner container">
     <h3>{{ story.name }}</h3>
     <p>{{ story.published_date }}</p>
     <img src="{% static 'kasi/images/trueWinner.jpg' %}" height="500px" width="900px">
     <div class="summary container">
       <h4>Summary</h4>
       <p>{{ story.summary }} </p>
     </div>
     <div class="pdf container">
       <embed src="{% static 'kasi/pdf/trueWinner.pdf' %}" width="200px" height="300px" />
       <a href="{% static 'kasi/pdf/trueWinner.pdf' %}"><p>Download PDF</p></a>
     </div>
   </div>
  {% endfor %}
</div>
{% endblock %}

{% block Comment %}
<div class="comments container">
  <a href="{% url 'kasi:comment' %}">Leave a comment</a>
  <p>Total number of comments: {{ comments.count }}</p>
  {% for comment in comments %}
      <p>{{ comment.comment_text }} - {{ comment.user }}</p>
  {% endfor %}

</div>
{% endblock %}